"""
FlowForge v0.2 - 内置模板
5 种 Agent 协作模式，每个 LLM/Tool/Retriever/Subagent 节点由 OpenCode Agent 驱动。
"""
from ..config import ANTHROPIC_MODEL

TEMPLATES: dict[str, dict] = {
    "supervisor_worker": {
        "name": "supervisor_worker",
        "display_name": "Supervisor-Worker",
        "description": "主管 Agent 拆解任务分发给多个 Worker，汇总结果",
        "canvas_data": {
            "nodes": [
                {"id": "supervisor", "type": "llm", "label": "Supervisor",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 30, "timeout_seconds": 600,
                            "system_prompt": "你是主管，只负责拆解任务，不负责执行。将用户问题拆为3个独立子任务，用格式输出：[Worker1]具体任务 [Worker2]具体任务 [Worker3]具体任务。不要自己执行任何任务。",
                            "user_prompt_template": "{{input}}"},
                 "position": {"x": 400, "y": 50}},
                {"id": "worker_1", "type": "llm", "label": "Worker 1",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 20, "timeout_seconds": 300,
                            "system_prompt": "你是 Worker 1。根据主管指令中的 [Worker1] 部分完成任务。只输出结果。",
                            "user_prompt_template": "主管指令：\n{{supervisor.output}}"},
                 "position": {"x": 100, "y": 250}},
                {"id": "worker_2", "type": "llm", "label": "Worker 2",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 20, "timeout_seconds": 300,
                            "system_prompt": "你是 Worker 2。根据主管指令中的 [Worker2] 部分完成任务。只输出结果。",
                            "user_prompt_template": "主管指令：\n{{supervisor.output}}"},
                 "position": {"x": 400, "y": 250}},
                {"id": "worker_3", "type": "tool", "label": "Worker 3 (Tool)",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "timeout_seconds": 300,
                            "tool_task": "主管指令: {{supervisor.output}}。根据上面主管指令中的 [Worker3] 部分，使用工具完成任务。"},
                 "position": {"x": 700, "y": 250}},
                {"id": "aggregator", "type": "llm", "label": "Aggregator",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 20, "timeout_seconds": 300,
                            "system_prompt": "综合三个 Worker 的结果，给用户一个简洁完整的最终回答。",
                            "user_prompt_template": "Worker1: {{worker_1.output}}\nWorker2: {{worker_2.output}}\nWorker3: {{worker_3.output}}"},
                 "position": {"x": 400, "y": 450}},
            ],
            "edges": [
                {"source": "supervisor", "target": "worker_1"},
                {"source": "supervisor", "target": "worker_2"},
                {"source": "supervisor", "target": "worker_3"},
                {"source": "worker_1", "target": "aggregator"},
                {"source": "worker_2", "target": "aggregator"},
                {"source": "worker_3", "target": "aggregator"},
            ],
        },
    },

    "sequential_chain": {
        "name": "sequential_chain",
        "display_name": "Sequential Chain",
        "description": "节点串行执行，每步只做分内事，输出传递到下一步",
        "canvas_data": {
            "nodes": [
                {"id": "step_1", "type": "llm", "label": "Step 1: Analyze",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "You are Step 1 ONLY. Do NOT do other steps' work. Your ONLY job: count lines of code as specified. Output ONLY the raw numbers, no analysis, no report.",
                            "user_prompt_template": "{{input}}"},
                 "position": {"x": 400, "y": 50}},
                {"id": "step_2", "type": "llm", "label": "Step 2: Reason",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "You are Step 2 ONLY. Do NOT do step 1 or step 3's work. Your ONLY job: take the numbers from Step 1 and do the calculation specified. Output ONLY the calculation result, no analysis.",
                            "user_prompt_template": "Step 1 output:\n{{step_1.output}}"},
                 "position": {"x": 400, "y": 200}},
                {"id": "step_3", "type": "tool", "label": "Step 3: Execute",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "timeout_seconds": 60,
                            "tool_task": "Step 2 result:\n{{step_2.output}}\n\nYou are Step 3 ONLY. Do NOT do other steps' work. Your ONLY job: execute the calculation or verification specified. Output ONLY the result number."},
                 "position": {"x": 400, "y": 350}},
                {"id": "step_4", "type": "llm", "label": "Step 4: Summarize",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "You are Step 4 ONLY. Combine previous steps' results into ONE final answer. Be concise. Do NOT redo previous work.",
                            "user_prompt_template": "Step 1: {{step_1.output}}\nStep 2: {{step_2.output}}\nStep 3: {{step_3.output}}"},
                 "position": {"x": 400, "y": 500}},
            ],
            "edges": [
                {"source": "step_1", "target": "step_2"},
                {"source": "step_2", "target": "step_3"},
                {"source": "step_3", "target": "step_4"},
            ],
        },
    },

    "parallel": {
        "name": "parallel",
        "display_name": "Parallel Experts",
        "description": "3个专家同时独立分析同一问题后汇总。与Supervisor区别：无主管拆解任务，专家各自从不同视角分析原始输入。",
        "canvas_data": {
            "nodes": [
                {"id": "fan_out", "type": "tool", "label": "Fan-Out (no-op)",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "timeout_seconds": 30,
                            "tool_task": "Output the word READY. Nothing else."},
                 "position": {"x": 400, "y": 50}},
                {"id": "expert_a", "type": "llm", "label": "Expert A: Facts",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "Answer from a factual perspective. Be concise.",
                            "user_prompt_template": "{{input}}"},
                 "position": {"x": 100, "y": 250}},
                {"id": "expert_b", "type": "llm", "label": "Expert B: Logic",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "Answer from a logical reasoning perspective. Be concise.",
                            "user_prompt_template": "{{input}}"},
                 "position": {"x": 400, "y": 250}},
                {"id": "expert_c", "type": "tool", "label": "Expert C: Tools",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "timeout_seconds": 60,
                            "tool_task": "Search for or compute the answer. Output ONLY the result."},
                 "position": {"x": 700, "y": 250}},
                {"id": "merger", "type": "llm", "label": "Merger",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 8, "timeout_seconds": 60,
                            "system_prompt": "Synthesize the three independent expert opinions into one final answer.",
                            "user_prompt_template": "Expert A: {{expert_a.output}}\nExpert B: {{expert_b.output}}\nExpert C: {{expert_c.output}}"},
                 "position": {"x": 400, "y": 450}},
            ],
            "edges": [
                {"source": "fan_out", "target": "expert_a"},
                {"source": "fan_out", "target": "expert_b"},
                {"source": "fan_out", "target": "expert_c"},
                {"source": "expert_a", "target": "merger"},
                {"source": "expert_b", "target": "merger"},
                {"source": "expert_c", "target": "merger"},
            ],
        },
    },

    "conditional_branch": {
        "name": "conditional_branch",
        "display_name": "Conditional Branch",
        "description": "根据条件判断走不同分支，最终汇总",
        "canvas_data": {
            "nodes": [
                {"id": "classifier", "type": "llm", "label": "Classifier",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 3, "timeout_seconds": 30,
                            "system_prompt": "Classify the question. Output ONLY 'fact' or 'analysis'.",
                            "user_prompt_template": "{{input}}"},
                 "position": {"x": 400, "y": 50}},
                {"id": "condition_check", "type": "condition", "label": "Type?",
                 "config": {"field": "classifier.output", "operator": "contains", "value": "analysis"},
                 "position": {"x": 400, "y": 200}},
                {"id": "fact_handler", "type": "tool", "label": "Fact Lookup",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "timeout_seconds": 30,
                            "tool_task": "Look up the factual answer. Output ONLY the result."},
                 "position": {"x": 150, "y": 350}},
                {"id": "analysis_handler", "type": "llm", "label": "Deep Analysis",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "Provide a deep analysis. Be concise.",
                            "user_prompt_template": "{{input}}"},
                 "position": {"x": 650, "y": 350}},
                {"id": "finalizer", "type": "llm", "label": "Finalizer",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 5, "timeout_seconds": 60,
                            "system_prompt": "Produce the final answer based on the handler output.",
                            "user_prompt_template": "Handler output: {{fact_handler.output}}{{analysis_handler.output}}"},
                 "position": {"x": 400, "y": 500}},
            ],
            "edges": [
                {"source": "classifier", "target": "condition_check"},
                {"source": "condition_check", "target": "analysis_handler", "label": "true"},
                {"source": "condition_check", "target": "fact_handler", "label": "false"},
                {"source": "fact_handler", "target": "finalizer"},
                {"source": "analysis_handler", "target": "finalizer"},
            ],
        },
    },

    "reflection_loop": {
        "name": "reflection_loop",
        "display_name": "Reflection Loop",
        "description": "生成回答 → 反思 → 不满足则改进并重试，满足则退出",
        "canvas_data": {
            "nodes": [
                {"id": "generator", "type": "llm", "label": "Generator",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 3, "timeout_seconds": 60,
                            "system_prompt": "Generate an answer. Do NOT use any tools. Output ONLY the answer text.",
                            "user_prompt_template": "{{input}}{{improver.output}}"},
                 "position": {"x": 400, "y": 50}},
                {"id": "reflector", "type": "llm", "label": "Reflector",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 1, "timeout_seconds": 30,
                            "system_prompt": "You are a text evaluator. Do NOT use any tools. Read the answer below. Output ONLY 'SATISFIED' if correct, or 'NEEDS_IMPROVEMENT: reason' if not.",
                            "user_prompt_template": "Evaluate this answer:\n{{generator.output}}"},
                 "position": {"x": 400, "y": 200}},
                {"id": "quality_check", "type": "condition", "label": "Satisfied?",
                 "config": {"field": "reflector.output", "operator": "contains", "value": "SATISFIED"},
                 "position": {"x": 400, "y": 350}},
                {"id": "improver", "type": "llm", "label": "Improver",
                 "config": {"model_provider": "deepseek", "model_id": "deepseek-v4-pro",
                            "opencode_agent": "build", "max_steps": 3, "timeout_seconds": 60,
                            "system_prompt": "Improve the answer based on feedback. Do NOT use any tools. Output ONLY the improved answer text.",
                            "user_prompt_template": "Original:\n{{generator.output}}\n\nFeedback:\n{{reflector.output}}\n\nImproved version:"},
                 "position": {"x": 400, "y": 500}},
            ],
            "edges": [
                {"source": "generator", "target": "reflector"},
                {"source": "reflector", "target": "quality_check"},
                {"source": "quality_check", "target": "improver", "label": "false"},
                {"source": "improver", "target": "generator"},
            ],
        },
    },
}


def get_template(name: str) -> dict | None:
    return TEMPLATES.get(name)


def list_templates() -> list[dict]:
    return [
        {
            "name": t["name"],
            "display_name": t["display_name"],
            "description": t["description"],
            "node_count": len(t["canvas_data"]["nodes"]),
            "edge_count": len(t["canvas_data"]["edges"]),
        }
        for t in TEMPLATES.values()
    ]
